# Generated by Django 3.0.8 on 2020-07-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expansion', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=15)),
                ('board', models.IntegerField(choices=[(1, 'Beach'), (2, 'Winter'), (3, 'Desert'), (4, 'Field')])),
            ],
        ),
    ]
