# Generated by Django 3.0.8 on 2020-07-21 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scenario',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Expansion'),
        ),
    ]
