# Generated by Django 3.0.8 on 2020-07-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_auto_20200721_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='board',
            field=models.IntegerField(choices=[(1, 'Beach'), (2, 'Winter'), (3, 'Desert'), (4, 'Countryside')]),
        ),
        migrations.CreateModel(
            name='SubExpansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=25, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Expansion')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='sub_expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.SubExpansion'),
        ),
    ]
