# Generated by Django 3.0.8 on 2020-07-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_scenario_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='scenario_type',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Overlord'), (3, 'Breakthrough'), (4, 'Breaklord')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenario',
            name='board',
            field=models.IntegerField(choices=[(1, 'Countryside'), (2, 'Winter'), (3, 'Desert'), (4, 'Beach')]),
        ),
    ]
